### ISSUE TITLE
udev rules installation should be optional

### ISSUE THREAD

**Issue by smunaut** [xtrx-sdr/libxtrxll#1]
If you install in a non standard path ( e.g. I use -DCMAKE_INSTALL_PREFIX=/opt/xtrx ) : 
 - The destination isn't correct
 - It doesn't have the right to write file there anyway (I don't use sudo for install, my dest dir is user writable ).

**Comment by chemeris** [comment]
Optional = a `cmake` option or some other way?

**Comment by smunaut** [comment]
Yeah CMake option is fine. "INSTALL_UDEV_RULES" is what's used in rtl-sdr and hackrf (and others IIRC). Also the destination is always set as absolute rather than relative because the destination prefix can vary.

**Comment by chemeris** [comment]
I see. Could you point to an example or share a patch?

Written with a touchscreen keyboard. Please bear with typos and crazy
autocorrections.

--
Regards,
Alexander Chemeris.
CTO/Founder, Fairwaves, Inc.
https://fairwaves.co

**Comment by mnhauke** [comment]
https://github.com/xtrx-sdr/libxtrxll/pull/2

**Comment by chemeris** [comment]
PR #2 has been merged
