### ISSUE TITLE
What would cause a GPEP warning to occur?

### ISSUE THREAD

**Issue by nunnsy** [xtrx-sdr/libxtrxll#4]
Hi there,

I'm just wondering as to why this warning would be appearing for using the XTRX Pro over the USB3 adaptor/interface?

```
...
17:12:43.805347 WARN:   [USB3] USB3_4/2/3: GPEP idx 1 status: 1 (witten 0, res -65536)
17:12:44.030641 WARN:   [USB3] USB3_4/2/3: GPEP idx 0 status: 1 (witten 0, res -65536)
17:12:44.056162 WARN:   [USB3] USB3_4/2/3: GPEP idx 1 status: 1 (witten 0, res -65536)
17:12:44.281245 WARN:   [USB3] USB3_4/2/3: GPEP idx 0 status: 1 (witten 0, res -65536)
17:12:44.306983 WARN:   [USB3] USB3_4/2/3: GPEP idx 1 status: 1 (witten 0, res -65536)
17:12:44.531697 WARN:   [USB3] USB3_4/2/3: GPEP idx 0 status: 1 (witten 0, res -65536)
17:12:44.557813 WARN:   [USB3] USB3_4/2/3: GPEP idx 1 status: 1 (witten 0, res -65536)
...
```

For background, this is my current setup:
- Using a VM with Ubuntu for this testing, not sure about the interface speed with this extra 'layer'.
- Using SoapySDR to interface with the XTRX Pro via Python.
- Using multiple SDRs (a LimeSDR on another USB3 port for transmission, XTRX Pro used for receiving).

Further interface properties are here:
```
# 1.875 GHz
RX_BASEBAND_FREQUENCY = TX_BASEBAND_FREQUENCY
# 1 kHz
RX_FREQUENCY = TX_FREQUENCY
# In Hz (used for filtering, nothing to do with SDR parameters)
RX_FREQUENCY_BW = 1000
# Sample rate per channel
RX_SAMPLE_RATE = 2e6
# XTRX bandwidth
RX_BANDWIDTH = 1e6
# Used for SoapySDR to connect to the correct device.
RX_DEVICE = "xtrx"
# Channels used.
RX_CHANNEL = [0, 1]
# Antenna used on both channels.
RX_ANTENNA = "LNAH"
# Read stream timeout.
RX_TIMEOUT = 10000
# SDR gain.
RX_GAIN = 10

# How many signal of interest oscillations to capture (pure tone).
RX_OSCILLATIONS_TO_CAPTURE = 50
# Number of samples within one oscillation of the received tone.
RX_SAMPLES_PER_OSCILLATION = int(RX_SAMPLE_RATE / RX_FREQUENCY)
# How many samples to request in every stream read call.
RX_STREAM_BATCH_SIZE = int(RX_SAMPLES_PER_OSCILLATION * \
    RX_OSCILLATIONS_TO_CAPTURE)
```

I've traced the warning to this file within the XTRX USB3 library. I am, in the future, hoping to use a direct PCIe connection. In the mean time, I'm using the USB3 interface.

https://github.com/xtrx-sdr/libxtrxll/blob/50176aff00ae9e6196922c0e63d7f887b16b6340/mod_usb3380/xtrxll_libusb3380.c#L966-L968

I can't easily see as to why this warning would be occurring, given the code in the above linked file or my general setup.

I've tried reducing my sample rate to 50kHz and the warnings still persist. So I can't imagine it's to do with the USB3 bandwidth?

Any help or pointers as to where I should be looking, or any explanation as to what the logged warning message is, would would be greatly appreciated!

Kind regards

**Comment by nunnsy** [comment]
If this issue could be labelled a question, would also be appreciated :)

**Comment by bkerler** [comment]
This should be caused by a usb timeout : 

https://github.com/xtrx-sdr/libusb3380/blob/da900c76f1d34a2af104eda7ff3e6439c0f59241/libusb3380.c#L349-L351

So the real cause for this is happening in libusb3380 due to a usb timeout. This might be because data is being read although it's not yet available. Normally, this shouldn't be considered to be an issue or warning.

If this is true, replacing this line : 

https://github.com/xtrx-sdr/libxtrxll/blob/50176aff00ae9e6196922c0e63d7f887b16b6340/mod_usb3380/xtrxll_libusb3380.c#L953

with

```
if (gpep->base.status != DQS_SUCCESS && gpep->base.status != DQS_TIMEOUT ) {
```

should fix the issue.

**Comment by nunnsy** [comment]
> This should be caused by a usb timeout :
> 
> https://github.com/xtrx-sdr/libusb3380/blob/da900c76f1d34a2af104eda7ff3e6439c0f59241/libusb3380.c#L349-L351
> 
> So the real cause for this is happening in libusb3380 due to a usb timeout. This might be because data is being read although it's not yet available. Normally, this shouldn't be considered to be an issue or warning.
> 
> If this is true, replacing this line :
> 
> https://github.com/xtrx-sdr/libxtrxll/blob/50176aff00ae9e6196922c0e63d7f887b16b6340/mod_usb3380/xtrxll_libusb3380.c#L953
> 
> with
> 
> ```
> if (gpep->base.status != DQS_SUCCESS && gpep->base.status != DQS_TIMEOUT ) {
> ```
> 
> should fix the issue.

Thanks @bkerler! I'll try your suggestion and report back.

**Comment by nunnsy** [comment]
Turns out I had an issue where I wasn't reading the samples fast enough due to a bottleneck in storing/writing the samples to the computer's disk.

Wasn't able to try this solution, as when I tried to compile again I was getting errors. Though, this is likely to the configuration I had for testing my project. The fix may still work for others!

Thank you again @bkerler
